services:
  - type: web
    name: yocrify
    env: python
    buildCommand: |
      mkdir -p /data
      chmod 777 /data
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        value: https://yocrify.onrender.com/callback
    disk:
      name: yocrify-data
      mountPath: /data
      sizeGB: 1
